-- ==========================================================
-- IES IEDC Seed Data (PostgreSQL)
-- Verified Institutional Records (2016-present)
-- ==========================================================

-- Roles
INSERT INTO roles (id, name, description) VALUES
  ('role_super', 'Super Admin', 'Full system access and administrator management'),
  ('role_content', 'Content Admin', 'Manage events, workshops, news, resources, and gallery'),
  ('role_team', 'Team Admin', 'Manage team members and academic-year team archives'),
  ('role_achieve', 'Achievement Admin', 'Verify and manage student and institutional achievements')
ON CONFLICT (id) DO NOTHING;

-- Academic Years
INSERT INTO academic_years (id, year_name, is_current, notes) VALUES
  ('ay_25_26', '2025–26', TRUE, 'Current Academic Year - 2025-26 ExeCom & Activities'),
  ('ay_24_25', '2024–25', FALSE, 'Academic Year 2024-25 ExeCom & Activities'),
  ('ay_23_24', '2023–24', FALSE, 'Academic Year 2023-24 ExeCom & Activities')
ON CONFLICT (id) DO NOTHING;

-- Departments
INSERT INTO departments (id, code, name) VALUES
  ('dept_ce', 'CE', 'Civil Engineering'),
  ('dept_me', 'ME', 'Mechanical Engineering'),
  ('dept_cse', 'CSE', 'Computer Science & Engineering'),
  ('dept_eee', 'EEE', 'Electrical & Electronics Engineering'),
  ('dept_ece', 'ECE', 'Electronics & Communication Engineering'),
  ('dept_rai', 'R&AI', 'Robotics & Artificial Intelligence'),
  ('dept_ds', 'DS', 'Data Science'),
  ('dept_sh', 'S&H', 'Science & Humanities')
ON CONFLICT (id) DO NOTHING;

-- Team Members
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_01', '2025–26', 'Ms. Shahaziya Parvez M', 'Nodal Officer', 'Nodal Officer', 'R&AI', 'Assistant Professor / HOD', 'Coordinates IEDC activities.', 1, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_02', '2025–26', 'Ms. Prabhavathi P', 'Assistant Nodal Officer', 'Assistant Nodal Officer', 'S&H', 'Assistant Professor', 'Assists with coordination and implementation of activities.', 2, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_03', '2025–26', 'Rudhra V S', 'CEO', 'Chief Executive Officer (CEO)', 'ECE', '', 'Overall coordination of the IEDC.', 3, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_04', '2025–26', 'Ajmal P R', 'CEO', 'Chief Executive Officer (CEO)', 'CE', '', 'Overall coordination of the IEDC.', 4, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_05', '2025–26', 'Nidha', 'Women Lead', 'Women''s Innovation Lead', 'DS', '', 'Encourages women''s participation in entrepreneurship and innovation.', 5, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_06', '2025–26', 'Ajlan Nowshad', 'CMO', 'Chief Marketing Officer (CMO)', 'CSE', '', 'Publicity through notice boards, social media and newspapers.', 6, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_07', '2025–26', 'Fletteesh Thomas C', 'CMO', 'Chief Marketing Officer (CMO)', 'CSE', '', 'Publicity through notice boards, social media and newspapers.', 7, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_08', '2025–26', 'Avin', 'CTO', 'Chief Technical Officer (CTO)', 'ECE', '', 'Uploading forms and maintaining a link with Kerala Start-up Mission (KSUM).', 8, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_09', '2025–26', 'Abhijith N S', 'CTO', 'Chief Technical Officer (CTO)', 'ECE', '', 'Uploading forms and maintaining a link with Kerala Start-up Mission (KSUM).', 9, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_10', '2025–26', 'Vishnu A K', 'CFO', 'Chief Financial Officer (CFO)', 'ME', '', 'Handling financial related activities.', 10, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_11', '2025–26', 'Liya Siswana', 'CFO', 'Chief Financial Officer (CFO)', 'ECE', '', 'Handling financial related activities.', 11, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_12', '2025–26', 'Mohammad Fadil', 'Executive Lead', 'IIC Student Convener', 'CE', '', 'Coordination of IIC student convener operations.', 12, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_13', '2025–26', 'Minsha Badhar', 'Executive Lead', 'IIC Student Convener', 'CSE', '', 'Coordination of IIC student convener operations.', 13, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_14', '2025–26', 'Muhammed Muneef', 'CCO', 'Chief Creative Officer (CCO)', 'ME', '', 'Designing logo & poster and social media account maintenance.', 14, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_15', '2025–26', 'Ajay Ramesh', 'CCO', 'Chief Creative Officer (CCO)', 'CE', '', 'Designing logo & poster and social media account maintenance.', 15, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_16', '2025–26', 'Muhammed Ishan', 'Executive Lead', 'Chief Resource Officer (CRO)', 'CE', '', 'Resource management and lab coordination.', 16, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_17', '2025–26', 'Anitta Mariya', 'Executive Lead', 'Chief Resource Officer (CRO)', 'CSE', '', 'Resource management and lab coordination.', 17, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_18', '2025–26', 'Bhadra', 'Community Lead', 'Community Lead', 'EEE', '', 'Build and nurture a vibrant community of students, alumni, and mentors.', 18, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_19', '2025–26', 'Anagha Rose A S', 'Community Lead', 'Community Lead', 'ECE', '', 'Build and nurture a vibrant community of students, alumni, and mentors.', 19, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_20', '2025–26', 'Hana Hisham', 'Executive Lead', 'Chief Program Officer (CPO)', 'CE', '', 'Program planning and event execution.', 20, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_21', '2025–26', 'Shalbin Benny', 'Executive Lead', 'Chief Program Officer (CPO)', 'CSE', '', 'Program planning and event execution.', 21, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_22', '2025–26', 'Abhinav', 'IPR & Research Lead', 'IPR & Research Lead', 'CSE', '', 'Manages all startups about intellectual property rights (IPR) and its importance.', 22, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_23', '2025–26', 'Aliya K Ansari', 'IPR & Research Lead', 'IPR & Research Lead', 'CE', '', 'Manages all startups about intellectual property rights (IPR) and its importance.', 23, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_24', '2025–26', 'Faraz P M', 'COO', 'Chief Operating Officer (COO)', 'ME', '', 'File management, email, report making, and permission letters.', 24, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_25_25', '2025–26', 'Govind P S', 'COO', 'Chief Operating Officer (COO)', 'EEE', '', 'File management, email, report making, and permission letters.', 25, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_01', '2024–25', 'Ms. Shahaziya Parvez M', 'Nodal Officer', 'Nodal Officer', 'R&AI', 'Assistant Professor, R&AI HOD', 'Coordinates IEDC activities.', 1, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_02', '2024–25', 'Ms. Prabhavathi P.', 'Assistant Nodal Officer', 'Assistant Nodal Officer', 'S&H', 'Assistant Professor', 'Assists with coordination and implementation of activities.', 2, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_03', '2024–25', 'Ms. Angela C Joy', 'Department Coordinator', 'CE-Department IEDC Coordinator', 'CE', 'Assistant Professor', 'Coordinate IEDC activities within CE department.', 3, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_04', '2024–25', 'Mr. Anil D Coola', 'Department Coordinator', 'ME-Department IEDC Coordinator', 'ME', 'Assistant Professor', 'Coordinate IEDC activities within ME department.', 4, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_05', '2024–25', 'Ms. Athira E P', 'Department Coordinator', 'CSE-Department IEDC Coordinator', 'CSE', 'Assistant Professor', 'Coordinate IEDC activities within CSE department.', 5, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_06', '2024–25', 'Ms. Nivya K Venu', 'Department Coordinator', 'EEE-Department IEDC Coordinator', 'EEE', 'Assistant Professor', 'Coordinate IEDC activities within EEE department.', 6, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_07', '2024–25', 'Ms. Bency Varghese A', 'Department Coordinator', 'ECE-Department IEDC Coordinator', 'ECE', 'Assistant Professor', 'Coordinate IEDC activities within ECE department.', 7, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_08', '2024–25', 'Ms. Amitha M J', 'Department Coordinator', 'R&AI-Department IEDC Coordinator', 'R&AI', 'Assistant Professor', 'Coordinate IEDC activities within R&AI department.', 8, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_09', '2024–25', 'Ms. Priya', 'Department Coordinator', 'DS-Department IEDC Coordinator', 'DS', 'Assistant Professor', 'Coordinate IEDC activities within DS department.', 9, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_10', '2024–25', 'Edwin Joy', 'IEDC Lead', 'IEDC Lead', 'EEE', 'Student - Alumni', 'An IEDC alumni (Ex-CEO) to give guidance to all activities with experience.', 10, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_11', '2024–25', 'Fathima Dilsha', 'IEDC Lead', 'IEDC Lead', 'CSE', 'Student - Alumni', 'An IEDC alumni (Ex-CEO) to give guidance to all activities with experience.', 11, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_12', '2024–25', 'Ajmal P R', 'Student Lead', 'Student Lead I', 'CE', 'Student - CE', 'Overall coordination of the IEDC.', 12, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_13', '2024–25', 'Rudhra V S', 'Student Lead', 'Student Lead II', 'ECE', 'Student - ECE', 'Overall coordination of the IEDC.', 13, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_14', '2024–25', 'Nidha', 'Women Lead', 'Women''s Lead', 'DS', 'Student - DS', 'Encourage women''s participation in entrepreneurship and innovation.', 14, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_15', '2024–25', 'Govind P S', 'Executive Lead', 'Quality & Operations Lead I', 'EEE', 'Student - EEE', 'File management, reports, and operational coordination.', 15, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_16', '2024–25', 'Faraz', 'Executive Lead', 'Quality & Operations Lead II', 'ME', 'Student - ME', 'File management, reports, and operational coordination.', 16, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_17', '2024–25', 'Liya Siswana', 'Executive Lead', 'Finance Lead I', 'ECE', 'Student - ECE', 'Handling financial related activities.', 17, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_18', '2024–25', 'Vishnu', 'Executive Lead', 'Finance Lead II', 'ME', 'Student - ME', 'Handling financial related activities.', 18, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_19', '2024–25', 'Aliya K Ansari', 'IPR & Research Lead', 'IPR & Research Lead I', 'CE', 'Student - CE', 'Manages all startups about intellectual property rights (IPR).', 19, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_20', '2024–25', 'Abhinav', 'IPR & Research Lead', 'IPR & Research Lead II', 'CSE', 'Student - CSE', 'Manages all startups about intellectual property rights (IPR).', 20, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_21', '2024–25', 'Ajay Ramesh', 'Executive Lead', 'Creative & Innovation Lead I', 'CE', 'Student - CE', 'Designing logo & poster and social media account maintenance.', 21, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_22', '2024–25', 'Muneef', 'Executive Lead', 'Creative & Innovation Lead II', 'ME', 'Student - ME', 'Designing logo & poster and social media account maintenance.', 22, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_23', '2024–25', 'Anagha Rose', 'Community Lead', 'Community Lead I', 'ECE', 'Student - ECE', 'Build and nurture a vibrant community of students, alumni, and mentors.', 23, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_24', '2024–25', 'Bhadra', 'Community Lead', 'Community Lead II', 'EEE', 'Student - EEE', 'Build and nurture a vibrant community of students, alumni, and mentors.', 24, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_25', '2024–25', 'Shalbin Benny', 'Executive Lead', 'Program Lead I', 'CSE', 'Student - CSE', 'Program management and event planning.', 25, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_26', '2024–25', 'Hana Hisham', 'Executive Lead', 'Program Lead II', 'CE', 'Student - CE', 'Program management and event planning.', 26, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_27', '2024–25', 'Fletteesh Thomas C', 'CMO', 'Branding & Marketing Lead I', 'CSE', 'Student - CSE', 'Publicity through notice boards, social media and newspapers.', 27, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_28', '2024–25', 'Ajlan', 'CMO', 'Branding & Marketing Lead II', 'CSE', 'Student - CSE', 'Publicity through notice boards, social media and newspapers.', 28, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_29', '2024–25', 'Abhijith N S', 'Executive Lead', 'Web Dev Lead I', 'ECE', 'Student - ECE', 'Web portal design, development, and technical maintenance.', 29, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_30', '2024–25', 'Anamika', 'Executive Lead', 'Web Dev Lead II', 'CSE', 'Student - CSE', 'Web portal design, development, and technical maintenance.', 30, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_31', '2024–25', 'Anitta', 'Executive Lead', 'Resource Lead I', 'CSE', 'Student - CSE', 'Resource management and technical documentation.', 31, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_32', '2024–25', 'Ishan', 'Executive Lead', 'Resource Lead II', 'CE', 'Student - CE', 'Resource management and technical documentation.', 32, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_33', '2024–25', 'Minsha', 'Executive Lead', 'Students Convener', 'CSE', 'Student - CSE', 'Student convener and community coordination.', 33, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_24_34', '2024–25', 'Fadhil', 'Executive Lead', 'Students Convener', 'CE', 'Student - CE', 'Student convener and community coordination.', 34, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_01', '2023–24', 'Ms. Shahaziya Parvez M', 'Nodal Officer', 'Nodal Officer', 'ECE', 'Assistant Professor', 'Coordinates IEDC activities.', 1, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_02', '2023–24', 'Ms. Prabhavathi P.', 'Assistant Nodal Officer', 'Assistant Nodal Officer', 'S&H', 'Assistant Professor', 'Assists with coordination and implementation of activities.', 2, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_03', '2023–24', 'Ms. Oshin Ann Mathew', 'Department Coordinator', 'CE-Department IEDC Coordinator', 'CE', 'Assistant Professor', 'Coordinate IEDC activities within CE department.', 3, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_04', '2023–24', 'Mr. Anil D Coola', 'Department Coordinator', 'ME-Department IEDC Coordinator', 'ME', 'Assistant Professor', 'Coordinate IEDC activities within ME department.', 4, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_05', '2023–24', 'Ms. Anaswara Dinesh', 'Department Coordinator', 'CSE-Department IEDC Coordinator', 'CSE', 'Assistant Professor', 'Coordinate IEDC activities within CSE department.', 5, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_06', '2023–24', 'Ms. Anitha Mathew', 'Department Coordinator', 'EEE-Department IEDC Coordinator', 'EEE', 'Assistant Professor', 'Coordinate IEDC activities within EEE department.', 6, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_07', '2023–24', 'Ms. Bency Varghese A', 'Department Coordinator', 'ECE-Department IEDC Coordinator', 'ECE', 'Assistant Professor', 'Coordinate IEDC activities within ECE department.', 7, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_08', '2023–24', 'Shabeer Mohammed CTP', 'IEDC Lead', 'IEDC Lead', 'CSE', 'Student - Alumni', 'An IEDC alumni (Ex-CEO) to give guidance to all activities with experience.', 8, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_09', '2023–24', 'Nafih Najeeb', 'IEDC Lead', 'IEDC Lead', 'ME', 'Student - Alumni', 'An IEDC alumni (Ex-CEO) to give guidance to all activities with experience.', 9, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_10', '2023–24', 'Shabir Ibrahim KB', 'Student Lead', 'Student Lead I', 'EEE', 'Student - EEE', 'Overall coordination of student activities.', 10, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_11', '2023–24', 'Leslin', 'Women Lead', 'Student Women Lead - Craft Allies', 'EEE', 'Student - EEE', 'Encourages women''s participation in entrepreneurship.', 11, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_12', '2023–24', 'Angio James', 'Executive Lead', 'Quality & Operations Lead', 'EEE', 'Student - EEE', 'File management, email, report making, and permission letters.', 12, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_13', '2023–24', 'Abin', 'Executive Lead', 'Quality & Operations Lead', 'ME', 'Student - ME', 'File management, email, report making, and permission letters.', 13, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_14', '2023–24', 'Amaldeep Biju', 'Executive Lead', 'Finance Lead', 'ECE', 'Student - ECE', 'Handling financial related activities.', 14, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_15', '2023–24', 'Sandra P S', 'IPR & Research Lead', 'IPR & Research Lead', 'CE', 'Student - CE', 'Manages all startups about intellectual property rights (IPR).', 15, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_16', '2023–24', 'Godwin CS', 'Executive Lead', 'Finance Lead', 'EEE', 'Student - EEE', 'Handling financial related activities.', 16, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_17', '2023–24', 'Agnel Christy Raison', 'Executive Lead', 'Creative & Innovation Lead', 'EEE', 'Student - EEE', 'Designing logo & poster and social media account maintenance.', 17, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_18', '2023–24', 'Abhinav V R', 'Executive Lead', 'Creative & Innovation Lead', 'EEE', 'Student - EEE', 'Designing logo & poster and social media account maintenance.', 18, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_19', '2023–24', 'Himal Bentom', 'Community Lead', 'Community Lead', 'ECE', 'Student - ECE', 'Build and nurture a vibrant community of students, alumni, and mentors.', 19, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_20', '2023–24', 'Joel Joby', 'Community Lead', 'Community Lead', 'ME', 'Student - ME', 'Build and nurture a vibrant community of students, alumni, and mentors.', 20, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_21', '2023–24', 'Kebin', 'CTO', 'Technology Lead', 'EEE', 'Student - EEE', 'Uploading forms and maintaining a link with KSUM.', 21, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_22', '2023–24', 'Harikrishnan T B', 'CTO', 'Technology Lead', 'EEE', 'Student - EEE', 'Uploading forms and maintaining a link with KSUM.', 22, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_23', '2023–24', 'Mohammed Salman', 'CMO', 'Branding & Marketing Lead', 'ECE', 'Student - ECE', 'Publicity through notice boards, social media and newspapers.', 23, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_24', '2023–24', 'Joel', 'CMO', 'Branding & Marketing Lead', 'EEE', 'Student - EEE', 'Publicity through notice boards, social media and newspapers.', 24, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_25', '2023–24', 'Shaikha', 'Core Member', 'Craft Allies', 'ECE', 'Student - ECE', 'Supports community innovation initiatives.', 25, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_26', '2023–24', 'Aliya', 'Core Member', 'Craft Allies', 'ECE', 'Student - ECE', 'Supports community innovation initiatives.', 26, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_27', '2023–24', 'Ananthakrishnan K U', 'Executive Lead', 'Web Dev Lead', 'ECE', 'Student - ECE', 'Web portal design, development, and technical maintenance.', 27, 'Published') ON CONFLICT (id) DO NOTHING;
INSERT INTO team_members (id, academic_year_id, name, role_type, position, department_code, designation, responsibility, sort_order, status) VALUES ('tm_23_28', '2023–24', 'Fariz', 'Executive Lead', 'Web Dev Lead', 'CSE', 'Student - CSE', 'Web portal design, development, and technical maintenance.', 28, 'Published') ON CONFLICT (id) DO NOTHING;

-- Events & Activities
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_01', 'orientation-program-2026', 'Orientation program', '2025–26', '21/03/2026', '2026-03-21', NULL, 'EEE Seminar Hall', false, 'IES IEDC', '["IEDC Nodal Officer & Student Leads"]'::jsonb, 'Orientation', 'Orientation session handled by IEDC nodal officer and IEDC student leads.', 104, NULL, 'Upcoming', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_02', 'innovation-workshop-2026', 'Innovation workshop', '2025–26', '28/02/2026', '2026-02-28', NULL, 'ONLINE', true, 'IES IEDC', '[]'::jsonb, 'Workshop', 'Virtual interactive workshop on design thinking, ideation, and problem discovery.', 50, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_03', 'hobbie-hub-workshop-2026', 'Hobbie Hub Workshop', '2025–26', '21/02/2026', '2026-02-21', NULL, 'EEE Seminar Hall', false, 'IES IEDC', '["IEDC Hobbie Hub Leads"]'::jsonb, 'Workshop', 'The session was handled by IEDC Hobbie Hub Leads to encourage student passion projects.', 40, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_04', 'webinar-on-ai-empowerment-2026', 'Webinar on Ai empowerment and Ai Tools', '2025–26', '17/02/2026', '2026-02-17', NULL, 'online', true, 'IES IEDC', '[]'::jsonb, 'Webinar', 'Exploration of AI tools, workflow automation, and modern developer productivity.', 30, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_05', '3d-workshop-feb-2026', '3D Workshop', '2025–26', '07/02/2026', '2026-02-07', NULL, 'CSE Lab 2', false, 'IES IEDC', '["IEDC Leads"]'::jsonb, 'Workshop', 'The session was handled by IEDC Leads covering physical prototype slicing and CAD modeling.', 40, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_06', 'ipr-workshop-jan-2026', 'IPR Workshop', '2025–26', '28/01/2026', '2026-01-28', NULL, 'Online Platform', true, 'IES IEDC', '["Dr Biju K"]'::jsonb, 'Workshop', 'Specialized IPR session handled by Dr Biju K on patent filings, trademark protection, and prior-art search.', 100, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_07', 'iedc-camp-jan-2026', 'IEDC Camp', '2025–26', '09/01/2026 To 10/01/2025', '2026-01-09', '2025-01-10', 'IES College of Engineering', false, 'IES IEDC', '[]'::jsonb, 'Camp', 'Bootcamp session organized by IES IEDC for student technopreneurs.', 42, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_08', 'prompt-engineering-jan-2026', 'Prompt Engineering', '2025–26', '03/01/2026', '2026-01-03', NULL, 'EEE Seminar Hall', false, 'IES IEDC', '["MS Angel babu"]'::jsonb, 'Workshop', 'The session was handled by MS Angel babu on system prompt crafting and generative AI applications.', 58, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_09', 'open-source-contribution-dec-2025', 'Open-source contribution session', '2025–26', '13/12/2025', '2025-12-13', NULL, 'Online', true, 'IES IEDC', '["Harinandhan k"]'::jsonb, 'Workshop', 'The session was handled by Harinandhan k guiding students on open-source repositories and Git PRs.', 35, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_10', 'leadership-training-st-jude-2025', 'Leadership Training program', '2025–26', '25/11/2025', '2025-11-25', NULL, 'St. Jude Public School, Kuttanellur', false, 'IES Engineering College and the Excise Department''s jointly organized', '[]'::jsonb, 'Training', 'School community outreach leadership programme.', NULL, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_11', 'leadership-training-st-josephs-2025', 'Leadership Training program', '2025–26', '09/10/2025', '2025-10-09', NULL, 'St. JosephS C GHSS Thrissur', false, 'IES Engineering College and the Excise Department''s jointly organized', '[]'::jsonb, 'Training', 'School community outreach leadership training session.', NULL, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_12', 'leadership-training-sree-rama-krishna-2025', 'Leadership Training program', '2025–26', '09/10/2025', '2025-10-09', NULL, 'Sree Rama Krishna Higher Secondary School', false, 'IES Engineering College and the Excise Department''s jointly organized', '[]'::jsonb, 'Training', 'Leadership training for secondary school students.', NULL, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_13', 'inauguration-startup-awareness-2025', 'Inauguration Startup Awareness and Leadership Training', '2025–26', '06/10/2025', '2025-10-06', NULL, 'Sree Rama Krishna Gurukula Vidya Mandir Higher Secondary School', false, 'IES Engineering College and the Excise Department Vimukthi Mission jointly organized', '[]'::jsonb, 'Training', 'Inaugural startup awareness seminar and leadership workshop.', NULL, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_14', 'leadership-training-pattikad-2025', 'Leadership Training program', '2025–26', '18/09/2025', '2025-09-18', NULL, 'GHSS Pattikad', false, 'IES Engineering College and the Excise Department Vimukthi Mission jointly organized', '[]'::jsonb, 'Training', 'Leadership development session for high school students.', NULL, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_15', 'iedc-team-launch-2025', 'IEDC Team launch', '2025–26', '20/09/2025', '2025-09-20', NULL, 'EEE Seminar Hall', false, 'IES IEDC', '["IEDC nodal officer and iedc student leads"]'::jsonb, 'Orientation', 'Formal launch session handled by IEDC nodal officer and student leads.', 60, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_16', 'ice-breaking-session-2025', 'Ice breaking session', '2025–26', '08/08/2025', '2025-08-08', NULL, 'EEE Seminar Hall', false, 'IES IEDC', '["IEDC nodal officer and iedc student leads"]'::jsonb, 'Orientation', 'The session was handled by IEDC nodal officer and iedc student leads for new recruits.', 250, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_25_17', 'iedc-fest-july-2025', 'IEDC fest', '2025–26', '17/07/2025', '2025-07-17', NULL, 'IES College of Engineering', false, 'Organized by IES IEDC', '[]'::jsonb, 'Other', 'Annual innovation fest with participating students from different engineering colleges.', NULL, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_01', 'idea-pitching-mar-2025', 'Idea pitching', '2024–25', '22/03/2025', '2025-03-22', NULL, 'IEDC Room', false, 'Organized by IES IEDC', '[]'::jsonb, 'Ideation', 'Competitive student idea pitching event evaluated by panel.', NULL, 10, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_02', 'web-development-workshop-mar-2025', 'Web development workshop', '2024–25', '06/03/2025', '2025-03-06', NULL, 'Cse lab 2', false, 'Organized by IES IEDC', '["Nijo nelson","Michelle Aijo"]'::jsonb, 'Workshop', 'Session handled by Nijo nelson and Michelle Aijo on frontend building.', 55, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_03', 'ipr-session-feb-2025', 'Ipr session', '2024–25', '25/02/2025', '2025-02-25', NULL, 'ONLINE', true, 'IES IEDC', '["Dr Joe Gnanaraj (AP/Dept Of Mech Eng, St Mother Theresa Eng College)"]'::jsonb, 'Webinar', 'The Session Was Handled By Dr Joe Gnanaraj on IPR and patent registration.', 30, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_04', 'linkedin-workshop-jan-13-2025', 'LinkedIn workshop', '2024–25', '13/01/2025', '2025-01-13', NULL, 'Room no 323', false, 'IES IEDC', '["CEO of IEDC"]'::jsonb, 'Workshop', 'The session was handled by CEO of IEDC on digital branding.', 20, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_05', 'linkedin-workshop-jan-18-2025', 'LinkedIn workshop', '2024–25', '18/01/2025', '2025-01-18', NULL, 'Room no 323', false, 'IES IEDC', '["CEO of IEDC"]'::jsonb, 'Workshop', 'The session was handled by CEO of IEDC for student technopreneurs.', 50, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_06', 'leadership-training-ramvarmapuram-2024', 'Leadership Training programme', '2024–25', '26/12/2024', '2024-12-26', NULL, 'GVHS Ramvarmapuram', false, 'IES Engineering College and the Excise Department Vimukthi Mission jointly organized', '[]'::jsonb, 'Training', 'Leadership training for school students.', NULL, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_07', 'leadership-training-manthala-2024', 'Leadership Training programme', '2024–25', '22/12/2024', '2024-12-22', NULL, 'GHSS Manthala', false, 'IES Engineering College and the Excise Department Vimukthi Mission jointly organized', '[]'::jsonb, 'Training', 'Leadership training for school students.', NULL, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_08', 'seminar-on-ai-pattikad-2024', 'seminar on the Artificial Intelligence', '2024–25', '28/11/2024', '2024-11-28', NULL, 'GHSS Pattikad', false, 'IES Engineering College and the Excise Department Vimukthi Mission jointly organized', '[]'::jsonb, 'Seminar', 'Artificial Intelligence awareness seminar for school students.', NULL, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_09', 'linkedin-workshop-nov-18-2024', 'LinkedIn workshop', '2024–25', '18/11/2024', '2024-11-18', NULL, 'Room no 323', false, 'IES IEDC', '["AFSHAD K A"]'::jsonb, 'Workshop', 'The session was handled by AFSHAD K A on career networking.', 25, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_10', 'orientation-session-oct-2024', 'Orientation session', '2024–25', '29/10/2024 To 30/10/2024', '2024-10-29', '2024-10-30', 'EEE Seminar Hall', false, 'IES IEDC', '["IEDC nodal officer and IEDC student leads"]'::jsonb, 'Orientation', 'Two-day orientation session handled by IEDC nodal officer and student leads.', 104, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_11', 'sih-internal-hackathon-sep-2024', 'SIH Internal Hackathon', '2024–25', '12/09/2024', '2024-09-12', NULL, 'Room no 108', false, 'Organized by IES IEDC for Smart India Hackathon', '[]'::jsonb, 'Hackathon', 'Internal hackathon selection for Smart India Hackathon.', NULL, 32, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_12', '3d-workshop-oct-2024', '3D workshop', '2024–25', '16/10/2024', '2024-10-16', NULL, 'Room no 117', false, 'IES IEDC', '["Abilash Ps","Abhijith N S"]'::jsonb, 'Workshop', 'The session was handled by Abilash Ps & Abhijith N S on additive manufacturing.', 17, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_13', 'seminar-on-ai-avanoor-2024', 'seminar on the Artificial Intelligence', '2024–25', '28/10/2024', '2024-10-28', NULL, 'Shantha School Avanoor', false, 'IES Engineering College and the Excise Department Vimukthi Mission jointly organized', '[]'::jsonb, 'Seminar', 'Seminar on Artificial Intelligence for school students.', NULL, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_14', 'orientation-future-robotics-ai-2024', 'Orientation about the future of robotics and ai', '2024–25', '12/09/2024', '2024-09-12', NULL, 'Room no 323', false, 'Conducted by RAI in association with IEDC', '["Mr Aravind","Mr Adarsh"]'::jsonb, 'Orientation', 'The session was handled by Mr Aravind and Mr Adarsh on autonomous controls and robotics.', 25, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_24_15', 'iedc-camp-aug-2024', 'IEDC Camp', '2024–25', '17/08/2024 To 18/08/2024', '2024-08-17', '2024-08-18', 'IES College of Engineering', false, 'Organized by IES IEDC', '[]'::jsonb, 'Camp', 'Two-day immersive innovation camp.', 60, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_01', 'iedc-fest-apr-2024', 'IEDC FEST', '2023–24', '08/04/2024 To 09/04/2024', '2024-04-08', '2024-04-09', 'IES college of Engineering', false, 'Organized by IES IEDC.', '[]'::jsonb, 'Other', 'Annual IEDC Fest showcasing student innovations with participants from different colleges.', NULL, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_02', 'webinar-on-importance-of-ipr-2024', 'Webinar On Importance Of IPR', '2023–24', '26/03/2024', '2024-03-26', NULL, 'ONLINE', true, 'IES IEDC', '["Dr Joe Gnanaraj (Ap/Dept Of Mech Engineering From St Mother Theresa Engineering College)"]'::jsonb, 'Webinar', 'The Session Was Handled By Dr Joe Gnanaraj on IPR awareness.', 36, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_03', 'seminar-energy-conservation-2024', 'Seminar On Energy Conservation Through Power Quality', '2023–24', '25/03/2024', '2024-03-25', NULL, 'EEE Seminar Hall', false, 'conducted by EEE Dept in association with IEEE', '[]'::jsonb, 'Seminar', 'Technical seminar on electrical power quality and energy conservation.', 87, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_04', 'industrial-visit-substation-2024', 'Industrial Visit To IES Substation And Solar Panel', '2023–24', '23/03/2024', '2024-03-23', NULL, 'IES substation and solar panel', false, 'Organized by EEE Dept in association with IEEE & EESA', '[]'::jsonb, 'Industry Visit', 'Practical field exposure to campus substation and solar infrastructure.', 15, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_05', '3d-printing-workshop-mar-2024', '3D Printing Workshop', '2023–24', '22/03/2024 To 23/03/2024', '2024-03-22', '2024-03-23', 'Cse Lab2', false, 'IES IEDC', '["Harikrishna","Abilash Ps","Abhijith N S"]'::jsonb, 'Workshop', 'Session Was Handled By Harikrishna, Abilash Ps & Abhijith N S.', 95, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_06', 'workshop-gen-ai-prompt-engineering-2024', 'Workshop on generative AI and prompt Engineering', '2023–24', '01/03/2024', '2024-03-01', NULL, 'Room no 307', false, 'Conducted by ECE dept in association with TECSA & IEDC for 1st year students of RAI, DS & EEE', '[]'::jsonb, 'Workshop', 'Generative AI and prompt engineering workshop.', 42, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_07', 'workshop-web-dev-python-2024', 'Workshop On Web Development Using Python Programming', '2023–24', '29/02/2024 To 1/03/2024', '2024-02-29', '2024-03-01', 'CSE LAB2 & CE CAD LAB', false, 'Conducted by ECE dept in association with IEDC', '[]'::jsonb, 'Workshop', 'Python web development hands-on training.', 37, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_08', 'orientation-session-feb-2024', 'Orientation session', '2023–24', '26/02/2024 To 27/02/2024', '2024-02-26', '2024-02-27', 'EEE Seminar Hall', false, 'IES IEDC', '["IEDC nodal officer and IEDC student leads"]'::jsonb, 'Orientation', 'The session was handled by IEDC nodal officer and IEDC student leads.', 166, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_09', 'seminar-blending-innovation-2024', 'Seminar on Blending innovation and business acumen', '2023–24', '22/02/2024', '2024-02-22', NULL, 'EEE Seminar Hall', false, 'conducted by EEE Dept in association with IEDC', '[]'::jsonb, 'Seminar', 'Seminar on blending technical innovation with commercial business acumen.', 114, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_10', 'iedc-bootcamp-nov-2023', 'IEDC Bootcamp', '2023–24', '27/11/2023 TO 28/11/2023', '2023-11-27', '2023-11-28', 'IES Auditorium', false, 'IES IEDC', '["Founder & CEO starting trouble"]'::jsonb, 'Camp', 'Conducted by founder & CEO starting trouble.', 135, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_11', '3d-printing-workshop-nov-2023', '3D printing Workshop', '2023–24', '21/11/2023', '2023-11-21', NULL, 'Mechanical lab', false, 'Organized by IES IEDC', '["Mr Abdul Rashid C"]'::jsonb, 'Workshop', 'The session was handled by Mr Abdul Rashid C.', 56, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_12', 'iedc-summit-oct-2023', 'IEDC Submit', '2023–24', '12/10/2023', '2023-10-12', NULL, 'CET Trivandrum', false, 'Organized by Kerala startup mission', '[]'::jsonb, 'Other', 'Statewide IEDC Summit at CET Trivandrum.', 28, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_13', 'nasa-space-app-challenge-2023', 'NASA Space app Challenge Bootcamp', '2023–24', '26/09/2023', '2023-09-26', NULL, 'IES Auditorium', false, 'Organized by IES IEDC', '[]'::jsonb, 'Camp', 'Bootcamp for NASA Space Apps Challenge hackathon.', 110, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_14', 'sih-internal-hackathon-sep-2023', 'SIH Internal Hackathon', '2023–24', '18/09/2023', '2023-09-18', NULL, 'Online Platform Google Meet', true, 'Organized by IES IEDC for Smart India Hackathon', '[]'::jsonb, 'Hackathon', 'Internal hackathon selection for SIH.', NULL, 27, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_15', '3-day-workshop-arduino-2023', '3 Day workshop on Arduino', '2023–24', '13/09/2023 To 15/09/2023', '2023-09-13', '2023-09-15', 'Room No. 307', false, 'Organized by ThinkfoTech Conducted by ECE dept in association with IEDC', '[]'::jsonb, 'Workshop', 'Hands-on micro-controller and sensor interfacing workshop.', 56, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_16', 'teachers-day-eco-writz-2023', 'Teachers day &ECO WRITZ Startup inauguration', '2023–24', '05/09/2023', '2023-09-05', NULL, 'IES Auditorium', false, 'Organized by IES IEDC Collaboration by NSS unit 186', '[]'::jsonb, 'Other', 'Teachers Day celebration and ECO WRITZ startup inauguration.', NULL, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO events (id, slug, name, academic_year_id, display_date, start_date, end_date, venue, is_online, organizer, resource_persons, category, description, participants_count, teams_count, status, published) VALUES ('evt_23_17', 'iedc-orientation-program-aug-2023', 'IEDC orientation program', '2023–24', '2/08/2023', '2023-08-02', NULL, 'IES Auditorium', false, 'Organized by IES IEDC.', '["Mr. Pranav P accent tutors & head of sails Kerala region @eduport Pvt"]'::jsonb, 'Orientation', 'The session was handled by Mr. Pranav P accent tutors & head of sails Kerala region @eduport Pvt.', 50, NULL, 'Completed', true) ON CONFLICT (id) DO NOTHING;
